### ISSUE TITLE
Looking to get in touch

### ISSUE THREAD

**Issue by rotemandshaul** [aurora-mareviv/random_gen#1]
Hi there,

I used this code for a clinical trial, and I'm looking to get in touch as I have some follow-up questions. Please email me: rotem@petranker.com

Thanks!

**Comment by medicalc** [comment]
The app is completely open source.
This means that you can see the full code, both in the blog post and in the Shiny app itself.

You can interrogate the code and tweak to your needs.

Please don't forget to cite the app if used.

Any questions you can post in the comments below or propose changes using the GitHub interface.

**Comment by aurora-mareviv** [comment]
The app is completely open source.
This means that you can see the full code, both in the blog post and in the Shiny app itself.

You can interrogate the code and tweak to your needs.

Please don't forget to cite the app if used.

Any questions you can post in the comments below or propose changes using the GitHub interface.

**Comment by aurora-mareviv** [comment]
Issue closed, solved in https://aurora-mareviv.github.io/talesofr/2016/06/r-shiny-clinical-trials-randomization/

The app structure is just a user interface to mask the randomisation.

The randomisation "engine" is the sample() function in R, which in this case creates a random permutation of the rows (hence a random permutation of the treatments, which is what we want in a RCT)

Fortunately for R users, sample() has references and citations

See citations in: https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/sample
